---
- name: Perform optional versionscheck
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: Merge default and locale Users
  ansible.builtin.set_fact:
    _l3d_users__merged_users: "{{ l3d_users__default_users + l3d_users__local_users }}"

- name: Create ansible user with superuser permissions
  ansible.builtin.include_tasks:
    file: 'user_ansible.yml'
  when: l3d_users__create_ansible | bool

- name: Create Groups and Users
  ansible.builtin.include_tasks:
    file: 'users.yml'

- name: Manage SSH public keys
  ansible.builtin.include_tasks:
    file: 'pubkeys.yml'

- name: Set SSH public Keys for root
  ansible.builtin.include_tasks:
    file: 'root_ssh.yml'
  when: l3d_users__set_root_ssh_keys | bool
