---
- name: Restart SSHD Server
  become: true
  listen: 'systemctl restart sshd'
  ansible.builtin.systemd:
    name: "{{ l3d_users__sshd_service }}"
    state: restarted
  when: l3d_users__sshd__service is defined and ansible_service_mgr == 'systemd'
