---
- name: Restart SSHD Server
  become: true
  listen: 'systemctl restart sshd'
  ansible.builtin.systemd:
    name: "{{ l3d_users__sshd_service | default(sshd) }}"
    state: restarted
  when: nsible_service_mgr == 'systemd'
